### ISSUE TITLE
 when build.  mime Error

### ISSUE THREAD

**Issue by Sundayuu** [thgh/rollup-plugin-serve#102]
var lite = require('mime/lite');

           ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /root/workspace/node16-pnpm8-build/repo/node_modules/.pnpm/registry.npmmirror.com+mime@4.0.0/node_modules/mime/dist/src/index_lite.js from /root/workspace/node16-pnpm8-build/repo/node_modules/.pnpm/registry.npmmirror.com+rollup-plugin-serve@3.0.0/node_modules/rollup-plugin-serve/dist/index.cjs not supported.

Instead change the require of index_lite.js in /root/workspace/node16-pnpm8-build/repo/node_modules/.pnpm/registry.npmmirror.com+rollup-plugin-serve@3.0.0/node_modules/rollup-plugin-serve/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.

    at Object.<anonymous> (/root/workspace/node16-pnpm8-build/repo/node_modules/.pnpm/registry.npmmirror.com+rollup-plugin-serve@3.0.0/node_modules/rollup-plugin-serve/dist/index.cjs:7:12)

    at Object.<anonymous> (/root/workspace/node16-pnpm8-build/repo/node_modules/.pnpm/@toolkit+cli-plugin-rollup@1.1.0_@babel+core@7.12.13_tslib@2.4.0_typescript@4.7.4/node_modules/@toolkit/cli-plugin-rollup/lib/dev.config.js:6:15)

    at Object.<anonymous> (/root/workspace/node16-pnpm8-build/repo/node_modules/.pnpm/@toolkit+cli-plugin-rollup@1.1.0_@babel+core@7.12.13_tslib@2.4.0_typescript@4.7.4/node_modules/@toolkit/cli-plugin-rollup/bin/toolkit-cli-service.js:3:19) {

  code: 'ERR_REQUIRE_ESM'

}

**Comment by thgh** [comment]
Does it work using this version range `^2` in package.json?

**Comment by thgh** [comment]
For your information:
rollup-plugin-serve@^2 uses mime 2
rollup-plugin-serve@^3 uses mime 4

**Comment by drushbrook** [comment]
@thgh - according to the most downloaded versions of rollup-plugin-serve as reported by the npm version history (https://www.npmjs.com/package/rollup-plugin-serve?activeTab=versions) 
rollup-plugin-serve@1.0.1 uses mime>=2.0.3 which to my understanding will now use mime@4.0.0
rollup-plugin-serve@1.1.0 uses mime>=2.4.6 which to my understanding will now use mime@4.0.0
rollup-plugin-serve@2.0.2 uses mime>=2.4.6 which to my understanding will now use mime@4.0.0
rollup-plugin-serve@2.0.3 uses mime^3 which to my understanding will now use mime@3.0.0
rollup-plugin-serve@latest (3.0.0) uses mime^4

unfortunately I'm using a package that has a subdependancy for rollup-plugin-serve@^1.0.1 hence running into a similar mime error.

**Comment by thgh** [comment]
Sure, published the patch in rollup-plugin-serve@1.1.1 just now

**Comment by thgh** [comment]
I have never seen commonjs in rollup.config.js, consider using what's suggested in the [docs](https://rollupjs.org/configuration-options/#plugins). So refactor `require` / `module.exports` to `import` / `export default`

If you want to add support for that in this plugin, create a new folder in the test folder and add a test case.
